variables:
  GIT_SUBMODULE_STRATEGY: normal

image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

stages:
  - build_base
  - build
  - build_singularity

.build base image:
  stage: build_base
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR/base_image
      --dockerfile $CI_PROJECT_DIR/base_image/Dockerfile
      --destination $CI_REGISTRY_IMAGE:base
      --reproducible
  needs: []

build base image:master:
  extends: .build base image
  only:
    refs:
      - master
      - schedules
    changes:
      - base_image/**/*

build base image:scheduled:
  extends: .build base image
  only:
    refs:
      - schedules

build base image:manual:
  extends: .build base image
  when: manual

build image:
  stage: build
  only:
    # To ensure that CI_COMMIT_REF_SLUG exists
    refs:
      - branches
      - tags
  before_script:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - '[[ "$CI_COMMIT_REF_SLUG" == "master" ]] && export CI_REF="latest" || export CI_REF="$CI_COMMIT_REF_SLUG"'
  script:
    # Copy the CI config so that we can read the job specs from it.
    - /kaniko/executor
      --context $CI_PROJECT_DIR/main_image
      --dockerfile $CI_PROJECT_DIR/main_image/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_REF
      --build-arg SINGULARITY_URL=$(cat singularity_url)
      --reproducible
