image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

.kaniko_build:
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context $IMAGE_DIR
      --dockerfile $IMAGE_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE/combined:$IMAGE_TAG
      --reproducible

build image:
  extends: .kaniko_build
  variables:
    IMAGE_DIR: $CI_PROJECT_DIR/image
    IMAGE_TAG: $CI_COMMIT_REF_NAME
