#!/bin/bash

# Set the conda environment and package folder in the home folder
conda config --system --add envs_dirs /home/$NB_USER/.conda/envs
conda config --system --add pkgs_dirs /home/$NB_USER/.conda/pkgs

# Capture all *JUPYTER* environment variables for SSH logins via ~/.ssh/environment
SSH_USER_DIR="/home/$NB_USER/.ssh"
SSH_ENV_FILE="$SSH_USER_DIR/environment"
mkdir -p "$SSH_USER_DIR"
chown "$NB_UID:$NB_GID" "$SSH_USER_DIR"
chmod 700 "$SSH_USER_DIR"

SSH_ENV_FILE="$SSH_ENV_FILE" python3 - <<'PY'
import os
from pathlib import Path

target = Path(os.environ["SSH_ENV_FILE"])
lines = []
for key, value in sorted(os.environ.items()):
    if "JUPYTER" not in key:
        continue
    if any(ch in value for ch in "\n\r"):
        continue  # refuse multi-line values
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'{key}="{escaped}"')

if lines:
    content = "# Auto-generated by startup.sh\n" + "\n".join(lines) + "\n"
    target.write_text(content, encoding="utf-8")
else:
    try:
        target.unlink()
    except FileNotFoundError:
        pass
PY
if [ -f "$SSH_ENV_FILE" ]; then
    chown "$NB_UID:$NB_GID" "$SSH_ENV_FILE"
    chmod 600 "$SSH_ENV_FILE"
fi

## launch daemonized SSHD
mkdir -p /var/run/sshd
/usr/sbin/sshd
